packages:
  - apps/*
  - packages/*
  - plugins/*
allowBuilds:
  '@scarf/scarf': set this to true or false
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.2'
  - '@turbo/darwin-arm64@2.11.2'
  - '@turbo/linux-64@2.11.2'
  - '@turbo/linux-arm64@2.11.2'
  - '@turbo/windows-64@2.11.2'
  - '@turbo/windows-arm64@2.11.2'
  - turbo@2.11.2
  - svelte@5.57.1
