"""Generate synthetic 23andMe-format kits on real chip positions with random genotypes.

No real genome is used: positions come from the chip-loci manifest (positions
only) and reference bases from the reference-grch37 pack; genotypes are drawn
at random. The header says so, and does not start like a real export, so the
repository guard (scripts/check-no-genomes.sh) still passes.

    uv run --project tools/packkit python fixtures/synthetic-kits/generate.py --rows 5000 --out fixtures/synthetic-kits/synthetic-v5-small.txt
"""

import argparse
import glob
import random
from pathlib import Path

import pyarrow.compute as pc
import pyarrow.parquet as pq

REPO = Path(__file__).resolve().parents[2]
NAMES = {**{i: str(i) for i in range(1, 23)}, 23: "X", 24: "Y", 25: "MT"}
BASES = "ACGT"
# Always included so tests can rely on them: the LCT/MCM6 region on chr2.
KEEP = (2, 136_500_000, 136_700_000)

HEADER = """# Synthetic 23andMe-format file generated by genotype-workbench fixtures/synthetic-kits/generate.py.
# Not a real person: positions are real chip loci, genotypes are random (seed {seed}).
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# rsid\tchromosome\tposition\tgenotype
"""


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--rows", type=int, default=5000)
    p.add_argument("--chip", default="v5")
    p.add_argument("--seed", type=int, default=37)
    p.add_argument("--sex", choices=["male", "female"], default="male")
    p.add_argument("--out", type=Path, required=True)
    a = p.parse_args()
    rng = random.Random(a.seed)

    loci = pq.read_table(REPO / ".cache/packs/chip-loci.parquet")
    loci = loci.filter(pc.match_substring(loci["chips"], a.chip))
    ref = pq.read_table(glob.glob(str(REPO / "packs-dist/reference-grch37/*/*.parquet"))[-1])
    refmap = {(c, p): r for c, p, r in zip(ref["chrom"].to_pylist(), ref["pos"].to_pylist(), ref["ref"].to_pylist())}

    rows = list(zip(loci["chrom"].to_pylist(), loci["pos"].to_pylist(), loci["rsid"].to_pylist()))
    keep = [r for r in rows if r[0] == KEEP[0] and KEEP[1] <= r[1] <= KEEP[2]]
    rest = [r for r in rows if r not in set(keep)] if a.rows < len(rows) else rows
    if a.rows < len(rows):
        rest = rng.sample(rest, max(0, a.rows - len(keep)))
        rows = sorted(set(keep + rest))
    lines = [HEADER.format(seed=a.seed)]
    for chrom, pos, rsid in rows:
        if chrom == 24 and a.sex == "female":
            gt = "--"
        elif rsid.startswith("i") and rng.random() < 0.01:
            gt = rng.choice(["II", "DD", "DI"])
        elif rng.random() < 0.015:
            gt = "--"
        else:
            r = refmap.get((chrom, pos), rng.choice(BASES))
            alt = rng.choice([b for b in BASES if b != r])
            f = rng.choice([0.05, 0.2, 0.5])
            pair = [alt if rng.random() < f else r for _ in range(2)]
            haploid = chrom == 25 or (a.sex == "male" and chrom in (23, 24))
            gt = pair[0] if haploid else "".join(sorted(pair))
        lines.append(f"{rsid}\t{NAMES[chrom]}\t{pos}\t{gt}\n")
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("".join(lines))
    print(f"{len(rows)} rows -> {a.out}")


if __name__ == "__main__":
    main()
