"""Generate synthetic raw-data kits on real chip positions.

No real genome is used: positions come from the chip-loci manifest (positions
only) and reference bases from the reference-grch37 pack; genotypes are drawn
at random. Every header says so, and none starts like a real export, so the
repository guard (scripts/check-no-genomes.sh) still passes.

Two modes:

    # One unrelated person, in any supported vendor's format.
    uv run --project tools/packkit python fixtures/synthetic-kits/generate.py \
        --rows 5000 --out fixtures/synthetic-kits/synthetic-v5-small.txt

    # Two people with a known relationship, for kinship tests. Genotypes are
    # inherited through simulated meiosis over the genetic map, so the pair
    # really does share segments, and the truth is known by construction.
    uv run --project tools/packkit python fixtures/synthetic-kits/generate.py \
        --rows 5000 --pedigree parent-child --out-dir fixtures/synthetic-kits

A simulated relative of a *real* kit would be half a real person's genotypes.
This script never reads one, and such a file must never be committed.
"""

import argparse
import glob
import math
import random
from pathlib import Path

import pyarrow.compute as pc
import pyarrow.parquet as pq

REPO = Path(__file__).resolve().parents[2]
# chip-loci uses the locus crate's codes: X=23, Y=24, MT=25.
NAMES = {**{i: str(i) for i in range(1, 23)}, 23: "X", 24: "Y", 25: "MT"}
BASES = "ACGT"
TRANSITION = {"A": "G", "G": "A", "C": "T", "T": "C"}
# Always included so tests can rely on them: the LCT/MCM6 region on chr2.
KEEP = (2, 136_500_000, 136_700_000)
AUTOSOMES = set(range(1, 23))

HEADER = """# Synthetic 23andMe-format file generated by genotype-workbench fixtures/synthetic-kits/generate.py.
# Not a real person: positions are real chip loci, genotypes are random (seed {seed}).
# We are using reference human assembly build 37 (also known as Annotation Release 104).
# rsid\tchromosome\tposition\tgenotype
"""

ANCESTRY_HEADER = """#AncestryDNA raw data download
#Synthetic file generated by genotype-workbench fixtures/synthetic-kits/generate.py.
#Not a real person: positions are real chip loci, genotypes are random (seed {seed}).
#Data is formatted using human reference build 37 (also known as GRCh37).
rsid\tchromosome\tposition\tallele1\tallele2
"""

MYHERITAGE_HEADER = """# MyHeritage DNA raw data.
# Synthetic file generated by genotype-workbench fixtures/synthetic-kits/generate.py.
# Not a real person: positions are real chip loci, genotypes are random (seed {seed}).
RSID,CHROMOSOME,POSITION,RESULT
"""

# FamilyTreeDNA ships no comment banner at all; the column names are the header.
FTDNA_HEADER = """RSID,CHROMOSOME,POSITION,RESULT
"""

# AncestryDNA numbers the pseudoautosomal X 25 and MT 26.
ANCESTRY_CHROM = {**{i: str(i) for i in range(1, 23)}, 23: "23", 24: "24", 25: "26"}


# ---------------------------------------------------------------- loci and alleles


def load_loci(chip: str, rows: int, rng: random.Random):
    """Chip positions, always including the LCT/MCM6 window."""
    loci = pq.read_table(REPO / ".cache/packs/chip-loci.parquet")
    loci = loci.filter(pc.match_substring(loci["chips"], chip))
    all_rows = list(zip(loci["chrom"].to_pylist(), loci["pos"].to_pylist(), loci["rsid"].to_pylist()))
    if rows >= len(all_rows):
        return sorted(all_rows)
    keep = [r for r in all_rows if r[0] == KEEP[0] and KEEP[1] <= r[1] <= KEEP[2]]
    rest = rng.sample([r for r in all_rows if r not in set(keep)], max(0, rows - len(keep)))
    return sorted(set(keep + rest))


def load_reference() -> dict:
    ref = pq.read_table(glob.glob(str(REPO / "packs-dist/reference-grch37/*/*.parquet"))[-1])
    return {(c, p): r for c, p, r in zip(ref["chrom"].to_pylist(), ref["pos"].to_pylist(), ref["ref"].to_pylist())}


def load_genetic_map() -> dict:
    """Cumulative cM per locus, for simulating recombination. Empty if unbuilt."""
    found = glob.glob(str(REPO / "packs-dist/genetic-map/*/*.parquet"))
    if not found:
        return {}
    t = pq.read_table(found[-1])
    return {(c, p): cm for c, p, cm in zip(t["chrom"].to_pylist(), t["pos"].to_pylist(), t["cm"].to_pylist())}


def site_alleles(rows, refmap, rng):
    """Per locus: the reference base, one alternate, and its frequency.

    Drawn once and shared by everyone in a pedigree — two people can only be
    compared at a locus if they are being compared against the same alleles.
    """
    sites = []
    for chrom, pos, _rsid in rows:
        ref = refmap.get((chrom, pos)) or rng.choice(BASES)
        # Most human SNPs are transitions (A<->G, C<->T), as in real chip data.
        if rng.random() < 0.97:
            alt = TRANSITION[ref]
        else:
            alt = rng.choice([b for b in BASES if b not in (ref, TRANSITION[ref])])
        sites.append((ref, alt, rng.choice([0.05, 0.2, 0.5])))
    return sites


# ---------------------------------------------------------------- people


class Person:
    """Two haplotypes over the same loci, plus a sex. Phase is known here
    because we simulated it; a chip could never tell us."""

    def __init__(self, hap1, hap2, sex):
        self.hap1, self.hap2, self.sex = hap1, hap2, sex


def founder(sites, rng, sex) -> Person:
    draw = lambda: [alt if rng.random() < f else ref for ref, alt, f in sites]
    return Person(draw(), draw(), sex)


def gamete(person: Person, rows, cmmap, rng):
    """One haplotype, recombining between loci at the map's rate.

    Haldane's mapping function: over d centimorgans the chance of an odd number
    of crossovers is (1 - e^(-2d/100)) / 2. Between chromosomes, and wherever
    the map has nothing to say, the choice is free.
    """
    out = []
    current = rng.getrandbits(1)
    last_chrom, last_cm = None, None
    for i, (chrom, pos, _rsid) in enumerate(rows):
        cm = cmmap.get((chrom, pos))
        if chrom != last_chrom:
            current = rng.getrandbits(1)  # independent assortment
        elif cm is not None and last_cm is not None:
            d = abs(cm - last_cm)
            if rng.random() < (1 - math.exp(-2 * d / 100)) / 2:
                current ^= 1
        elif cm is None and last_cm is None:
            # No map: fall back to roughly 1 cM per Mb so segments still break.
            d = abs(pos - rows[i - 1][1]) / 1_000_000
            if rng.random() < (1 - math.exp(-2 * d / 100)) / 2:
                current ^= 1
        out.append((person.hap1 if current == 0 else person.hap2)[i])
        last_chrom, last_cm = chrom, cm
    return out


def child_of(father: Person, mother: Person, rows, cmmap, rng, sex) -> Person:
    return Person(gamete(father, rows, cmmap, rng), gamete(mother, rows, cmmap, rng), sex)


def genotypes(person: Person, rows, rng, nocall_rate=0.015):
    """What a chip would report: unphased pairs, haploid where it must be,
    and a scatter of no-calls."""
    out = []
    for i, (chrom, _pos, rsid) in enumerate(rows):
        if chrom == 24 and person.sex == "female":
            out.append(None)
            continue
        if rsid.startswith("i") and rng.random() < 0.01:
            out.append(rng.choice(["II", "DD", "DI"]))
            continue
        if rng.random() < nocall_rate:
            out.append(None)
            continue
        a, b = person.hap1[i], person.hap2[i]
        haploid = chrom == 25 or (person.sex == "male" and chrom in (23, 24))
        out.append(a if haploid else "".join(sorted((a, b))))
    return out


# ---------------------------------------------------------------- writers


def write_kit(path: Path, vendor: str, rows, calls, seed: int) -> None:
    lines = []
    if vendor == "23andme":
        lines.append(HEADER.format(seed=seed))
        for (chrom, pos, rsid), gt in zip(rows, calls):
            lines.append(f"{rsid}\t{NAMES[chrom]}\t{pos}\t{gt or '--'}\n")
    elif vendor == "ancestrydna":
        lines.append(ANCESTRY_HEADER.format(seed=seed))
        for (chrom, pos, rsid), gt in zip(rows, calls):
            # Ancestry always writes two allele columns; 0 0 is a no-call, and a
            # haploid call is written as a pair, which the normalizer collapses.
            a, b = ("0", "0") if not gt else (gt[0], gt[-1])
            lines.append(f"{rsid}\t{ANCESTRY_CHROM[chrom]}\t{pos}\t{a}\t{b}\n")
    elif vendor in ("myheritage", "familytreedna"):
        lines.append((MYHERITAGE_HEADER if vendor == "myheritage" else FTDNA_HEADER).format(seed=seed))
        for (chrom, pos, rsid), gt in zip(rows, calls):
            lines.append(f'"{rsid}","{NAMES[chrom]}","{pos}","{gt or "--"}"\n')
    else:
        raise SystemExit(f"unknown vendor {vendor}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(lines))
    print(f"{len(rows)} rows -> {path}")


# ---------------------------------------------------------------- pedigrees

# Each builds two people from founders. The comment is the truth a test may assert.
PEDIGREES = {
    "parent-child": "one parent and their child: every locus shares an allele",
    "siblings": "two children of the same two parents",
    "half-siblings": "two children sharing one parent",
    "first-cousins": "children of two siblings",
    "unrelated": "two founders, as a control",
}


def build_pair(kind: str, sites, rows, cmmap, rng, sex):
    """Return (personA, personB, labelA, labelB)."""
    make = lambda f, m: child_of(f, m, rows, cmmap, rng, sex)
    f1, m1 = founder(sites, rng, "male"), founder(sites, rng, "female")

    if kind == "unrelated":
        return f1, founder(sites, rng, sex), "founder-a", "founder-b"
    if kind == "parent-child":
        return f1, make(f1, m1), "parent", "child"
    if kind == "siblings":
        return make(f1, m1), make(f1, m1), "sibling-a", "sibling-b"
    if kind == "half-siblings":
        m2 = founder(sites, rng, "female")
        return make(f1, m1), make(f1, m2), "half-sibling-a", "half-sibling-b"
    if kind == "first-cousins":
        sib_a, sib_b = make(f1, m1), make(f1, m1)
        # Each sibling has a child with an unrelated partner.
        outside_a, outside_b = founder(sites, rng, "female"), founder(sites, rng, "female")
        sib_a.sex, sib_b.sex = "male", "male"
        return make(sib_a, outside_a), make(sib_b, outside_b), "cousin-a", "cousin-b"
    raise SystemExit(f"unknown pedigree {kind}; try one of {', '.join(PEDIGREES)}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--rows", type=int, default=5000)
    p.add_argument("--chip", default="v5")
    p.add_argument("--seed", type=int, default=37)
    p.add_argument("--sex", choices=["male", "female"], default="male")
    p.add_argument("--vendor", choices=["23andme", "ancestrydna", "myheritage", "familytreedna"], default="23andme")
    p.add_argument("--out", type=Path, help="single-kit mode: where to write")
    p.add_argument("--pedigree", choices=sorted(PEDIGREES), help="write a related pair instead")
    p.add_argument("--out-dir", type=Path, help="pedigree mode: directory for the pair")
    p.add_argument("--vendor-b", help="pedigree mode: format for the second kit (default: --vendor)")
    a = p.parse_args()
    rng = random.Random(a.seed)

    rows = load_loci(a.chip, a.rows, rng)
    sites = site_alleles(rows, load_reference(), rng)

    if not a.pedigree:
        if not a.out:
            raise SystemExit("--out is required without --pedigree")
        person = founder(sites, rng, a.sex)
        write_kit(a.out, a.vendor, rows, genotypes(person, rows, rng), a.seed)
        return

    if not a.out_dir:
        raise SystemExit("--out-dir is required with --pedigree")
    cmmap = load_genetic_map()
    if not cmmap:
        print("! no genetic-map pack found; falling back to ~1 cM/Mb, so segment lengths are approximate")

    left, right, label_a, label_b = build_pair(a.pedigree, sites, rows, cmmap, rng, a.sex)
    vendor_b = a.vendor_b or a.vendor
    write_kit(a.out_dir / f"synthetic-{label_a}.txt", a.vendor, rows, genotypes(left, rows, rng), a.seed)
    write_kit(a.out_dir / f"synthetic-{label_b}.txt", vendor_b, rows, genotypes(right, rows, rng), a.seed)
    print(f"relationship: {a.pedigree} — {PEDIGREES[a.pedigree]}")


if __name__ == "__main__":
    main()
