import { describe, expect, it } from 'vitest';
import { SYNTHETIC_HEADER, syntheticFile } from './synthetic';

/** A few positions on chr1, chrX, chrY and chrMT, as the reference pack gives them. */
const reference = {
  chrom: Uint8Array.from([1, 1, 1, 23, 24, 25]),
  pos: Uint32Array.from([100, 200, 300, 1000, 2000, 73]),
  base: Uint8Array.from([...'ACGTAG'].map((c) => c.charCodeAt(0))),
};

const read = async (file: File) => (await file.text()).split('\n').filter(Boolean);
const rows = (lines: string[]) => lines.filter((l) => !l.startsWith('#')).map((l) => l.split('\t'));

describe('a generated profile', () => {
  it('never begins the way a real export does', () => {
    const header = SYNTHETIC_HEADER(7, 'drawn');
    expect(header.startsWith('# Genotype Workbench synthetic profile')).toBe(true);
    // The openings scripts/check-no-genomes.sh treats as real.
    for (const real of ['# This data file generated by 23andMe', '#AncestryDNA raw data download', '# MyHeritage DNA raw data', 'RSID,CHROMOSOME']) {
      expect(header.includes(real)).toBe(false);
    }
  });

  it('says in its own header that it is not a person', () => {
    expect(SYNTHETIC_HEADER(7, 'drawn')).toMatch(/Not a person/);
    expect(SYNTHETIC_HEADER(7, 'drawn')).toMatch(/Nobody has this genome/);
  });

  it('states the build, so the importer can trust the positions', () => {
    expect(SYNTHETIC_HEADER(1, 'reference')).toMatch(/build 37/);
  });

  it('carries the reference base twice in reference mode', async () => {
    const lines = rows(await read(syntheticFile(reference, { mode: 'reference', seed: 1, sex: 'female' })));
    const autosomal = lines.filter((r) => /^\d+$/.test(r[1]!));
    expect(autosomal.map((r) => r[3])).toEqual(['AA', 'CC', 'GG']);
  });

  it('gives one copy where there is only one to have', async () => {
    const male = rows(await read(syntheticFile(reference, { mode: 'reference', seed: 1, sex: 'male' })));
    const by = (name: string) => male.find((r) => r[1] === name)?.[3];
    expect(by('X')).toBe('T'); // one X in a male
    expect(by('Y')).toBe('A');
    expect(by('MT')).toBe('G'); // mitochondria are always haploid
  });

  it('gives a female two X copies and no Y at all', async () => {
    const female = rows(await read(syntheticFile(reference, { mode: 'reference', seed: 1, sex: 'female' })));
    expect(female.find((r) => r[1] === 'X')?.[3]).toBe('TT');
    expect(female.some((r) => r[1] === 'Y')).toBe(false);
  });

  it('leaves the rsID empty rather than inventing one', async () => {
    const lines = rows(await read(syntheticFile(reference, { mode: 'drawn', seed: 3, sex: 'female' })));
    expect(lines.every((r) => r[0] === '')).toBe(true);
  });

  it('repeats exactly for the same seed, and differs for another', async () => {
    const one = await syntheticFile(reference, { mode: 'drawn', seed: 42, sex: 'female' }).text();
    const same = await syntheticFile(reference, { mode: 'drawn', seed: 42, sex: 'female' }).text();
    const other = await syntheticFile(reference, { mode: 'drawn', seed: 43, sex: 'female' }).text();
    expect(one).toBe(same);
    expect(one).not.toBe(other);
  });

  it('draws alleles, no-calls and some difference from the reference', async () => {
    const many = {
      chrom: new Uint8Array(4000).fill(1),
      pos: Uint32Array.from({ length: 4000 }, (_, i) => 1000 + i * 10),
      base: new Uint8Array(4000).fill('A'.charCodeAt(0)),
    };
    const lines = rows(await read(syntheticFile(many, { mode: 'drawn', seed: 9, sex: 'female' })));
    const calls = lines.map((r) => r[3]!);
    expect(calls).toHaveLength(4000);
    expect(calls.filter((c) => c === '--').length).toBeGreaterThan(20); // a real chip misses some
    expect(calls.some((c) => c !== 'AA' && c !== '--')).toBe(true); // and not everything is the reference
    // Every call is two sorted bases, or a no-call.
    expect(calls.every((c) => c === '--' || (c.length === 2 && c[0]! <= c[1]!))).toBe(true);
  });

  it('names the file after what it is', () => {
    expect(syntheticFile(reference, { mode: 'drawn', seed: 5, sex: 'male' }).name).toBe('synthetic-profile-drawn-5.txt');
  });
});
